spring:
  application:
    name: spring-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/springJPA
    username: postgres
    password: default
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
server:
  port: 8090